### ISSUE TITLE
Dated library

### ISSUE THREAD

**Issue by adamreisnz** [MindscapeHQ/raygun4node#119]
Kia ora team, we are hoping to switch over from Sentry to Raygun, but are bumping into the fact that this Node library seems to be very dated and not really up to speed with modern best practices. The guide for using this library that the Sentry app links to has been written in 2013, and the code examples show it.

Are there any plans to modernise this library in the near future?

It will be very hard for us to rewrite our current Sentry error handling boilerplate code to migrate this to the Raygun library, which still uses callbacks, and it seems we will lose a lot of vital functionality and ease of implementation in the process.

We really would like to migrate, but this seems to be a show stopper 😢

**Comment by Widdershin** [comment]
Kia ora @adamreisnz.

Thanks for your interest in raygun4node. Sorry that you've had a rough experience to start with.

I've had a look at the guide on the Raygun docs site. You're quite right that the code examples are very out of date, especially the recommendation to use the `domain` module.

We've done quite a bit of work on this module over the last eighteen months, including:

- TypeScript support
- Added a `batch` option for improved performance sending errors
- Added a `reportUncaughtExceptions` option for reporting unhandled exceptions without requiring the `domain` module 
- Upcoming breadcrumbs support built on top of `AsyncLocalStorage`

The released features have been documented in the README, but I'll update the guide on the Raygun docs website to reflect the new changes.

Thanks for the feedback around preferring a promise-based API instead of callbacks, this is definitely something we'll look into. In the meantime, a wrapper function can be used as a workaround:

```
const raygun = require('raygun');

const raygunClient = new raygun.Client().init({
  apiKey: 'your API key',
  batch: true,
  reportUncaughtExceptions: true
});

function sendError(error, customData, request, tags) {
  return new Promise((resolve, reject) => {
    function sendHandler(sendError, response) {
      if (sendError) {
        reject(sendError);
      } else {
        resolve(response);
      }
    }

    raygunClient.send(error, customData, sendHandler, request, tags);
  });
}

async function main() {
  await sendError(new Error('Example error'));
  console.log('Sent error.');
}
```

Are there any other pieces of functionality or implementation pain points that you'd like to see addressed?

**Comment by adamreisnz** [comment]
Thanks, yes, I am aware that I can make a promise wrapper, but it would be ideal if the library would support promises. It's 2021 after all, and callback hell is luckily a thing of the past and we can leverage modern constructs like async/await.

There's a few other things that I am missing, yes:
* Filtering out of errors/events _before_ they hit your servers and count as an event. We have a lot of client side errors that are irrelevant and shouldn't be reported to us as application errors. Same on server side where we occasionally get errors in integrations which we don't need to report on.
* The fact that I need to wrap all my code in a domain function seems overly complicated and cumbersome. Unless I'm misunderstanding that example, this is not practical to do in our app. We just need a synchronous method in the Raygun library to which we can pass an error. However, I note you have `raygunClient.send(err)`, so that might work.
* Setting the user with a function is cumbersome and impractical, as we don't always run in the context of a "request", but sometimes run in a worker or task context. 
* Same with passing tags and extra meta data via 3rd, 4th, 5th argument etc. This should ideally be a config object that is passed in as a single parameter.

In general, it feels like a pretty big step back compared to the Sentry JS library which will add a lot of overhead to our own code in order to maintain feature parity and keep error reporting working smoothly for us.

**Comment by paul-uz** [comment]
It's now 2024 and this library hasn't had an update in years.

**Comment by ProRedCat** [comment]
Hi all, we've got some work planned for this provider now which will include updating it to more modern practices. 

As part of this we'd like to know what features the community wants for this new version of the provider. I'll take all the suggestions and present them as part of the proposed changes.

I appreciate your patience with all of this. We should hopefully have some results for you soon!

**Comment by miquelbeltran** [comment]
I have created different tickets for the different suggestions in the comments thread, so we can develop each suggestion individually.

Except for this point here, as I believe this is already addressed with the async send method:

> The fact that I need to wrap all my code in a domain function seems overly complicated and cumbersome. Unless I'm misunderstanding that example, this is not practical to do in our app. We just need a synchronous method in the Raygun library to which we can pass an error. However, I note you have raygunClient.send(err), so that might work.

I will close this ticket, and instead we should continue addressing each one of the suggestion in their respective ticket.

Please let me know if I should reopen this ticket otherwise.
