### ISSUE TITLE
Development and Test environments

### ISSUE THREAD

**Issue by PrototypeAlex** [MindscapeHQ/raygun4node#17]
Hey guys, nice work on the module.

It'd be awesome if I could mock the raygunTransport on the client: Use case, it'd be awesome if I could log and notify through node-notifier in a development environment, and perhaps be stubbed out in a test environment.

Cheers :smile:

**Comment by fundead** [comment]
Apologies for the delay in reponse to this ticket! Closing this one for now as while it does seem cool and a good use case we haven't had any other requests for it the years since - we need to balance complexity and increasing the API surface too much. If anyone else wants it though feel free to open a new ticket and we'll pop it in.
