### ISSUE TITLE
Add browserify support

### ISSUE THREAD

**Issue by psirenny** [MindscapeHQ/raygun4node#18]
It would be awesome if raygun4node could be browserified so that it worked in the browser too. A lot of my javascript is shared between the server and the browser, making it difficult to toggle between using ragun4js and raygun4node.

**Comment by fundead** [comment]
As it has turned out over the years Raygun4JS and Raygun4Node have proven to be rather specialized as the environments, APIs and requirements are quite different. There's no current plans and no easy way forward to merge these providers and provide a first class experience across Node + the wide array of client environments Raygun4JS must support, so the best approach will be to have raygun4node running on the server and raygun4js in the client for the foreseeable future.
