### ISSUE TITLE
Can we pass custom data in the middleware error reporter?

### ISSUE THREAD

**Issue by bahmutov** [MindscapeHQ/raygun4node#29]
We can pass custom data in the `client.send` method, but the middleware does not allow this. Would be nice to set custom data when initializing the client (similar to the way `client.setVersion` keeps it) and then add these settings to the middleware exception.

**Comment by fundead** [comment]
Thanks for alerting us to this use case. This does indeed sounds valuable but we don't have any capacity to implement this immediately - as the provider is open sourced note we do accept pull requests if you are interested in having it in the main provider asap. Otherwise I have noted this down and will look at it again in the future.

Regards,

Callum Gavin
Mindscape Limited
