### ISSUE TITLE
APM for AWS Lambda?

### ISSUE THREAD

**Issue by paul-uz** [MindscapeHQ/raygun4node#318]
Looking at the docs, to use APM, an agent is required, which is not possible when using AWS Lambda.

We have Xray tracing, but at a cost. If we want to use Raygun APM, we can't from the looks of it.

Does this package provide any APM functionality?

Any way APM can be implemented for Lambda?

**Comment by sumitramanga** [comment]
Hi @paul-uz 

Thank you for your request! 

I've passed this over to our rostered support team for consideration and investigation. 

They'll let you know of their findings.

Cheers,
Sumitra

**Comment by PanosNB** [comment]
Hello Paul,

It is theoretically feasible but we have not tried it ourselves nor do we have ready-made aws-lambda docker images.

First off, that would only work for C#, Ruby and Node.js, the three languages we support APM.

Next, if you need this for Node.js or Ruby, you can put the agent on a separate virtualized OS because for these two, you can modify the APM agent's url and port that the profiler sends data to. If it is C# though, the APM Agent needs to be in the same OS as the profiled application.

So, if C#, you will need to set up a docker container image that is compatible with AWS lambda, and install both the APM agent and your C# application on it.

If Ruby or Node.js, you can set up the agent on an AWS lambda or an EC2 instance, create a VPC that they can see each other, and add your Node/Ruby apps with the Raygun profiler on their own lambda.

I have fiddled around with all these, so do reach out if you decide to undertake this project and I'll help you out as well! Also, if you do get this running, it might be a good opportunity for us to do a joint tech write-up!

Let me know what you think

Dr. Panos Patros, CPEng
VPEng at Raygun

**Comment by paul-uz** [comment]
Thanks for the reply @PanosNB !

In my case, I am only concerned with AWS Lambda. I'm curious to understand how the agent would run on AWS Lambda? Would it be a custom runtime?

**Comment by PanosNB** [comment]
Hi Paul,

No, it doesn't need a custom runtime. Just one that we already support (i.e., Ruby, .NET or Node.js). If you are thinking about writing code in the AWS lambda field directly, that won't work though. You'd need to set up an image with your function (that includes all of the above) and load that into what the AWS Lambda would execute.

Not sure if this answers your question. happy to have video call and discuss your use case though?

Dr. Panos Patros, CPEng
VPEng at Raygun

**Comment by paul-uz** [comment]
> Hi Paul,
> 
> No, it doesn't need a custom runtime. Just one that we already support (i.e., Ruby, .NET or Node.js). If you are thinking about writing code in the AWS lambda field directly, that won't work though. You'd need to set up an image with your function (that includes all of the above) and load that into what the AWS Lambda would execute.
> 
> Not sure if this answers your question. happy to have video call and discuss your use case though?
> 
> Dr. Panos Patros, CPEng
> VPEng at Raygun

Ah yes, so a Lambda Layer with a modified NodeJS image that has the APM agent on it?

**Comment by PanosNB** [comment]
Yes, you can do that. You *must* have the profiler in that image. The agent would also be ok to have but, for Node.JS APM, you could put the agent elsewhere so you don't spin up an agent every time the lambda scales out. To go for the second option, you'd need to set the IP that the profiler sends the packets to not be localhost, rather where you're hosting the agent.

**Comment by sumitramanga** [comment]
Hi @paul-uz Just checking in to see how you're going here! Did you find Panos' response useful or do you need any additional help? Do let us know :)

**Comment by paul-uz** [comment]
> Hi @paul-uz Just checking in to see how you're going here! Did you find Panos' response useful or do you need any additional help? Do let us know :) 

It was insightful yes. However it sounds like it's not something easily implemented in our ecosystem, so it's not something I'm looking to pursue at the time.

Thank you for asking :)

**Comment by sumitramanga** [comment]
Hi @paul-uz No worries, we can close this Issue in the meantime. When you get the chance to implement, and you have any issues, please let us know. We'll be more than happy to help!
