### ISSUE TITLE
sendSync for handling errors before a crash

### ISSUE THREAD

**Issue by GeorgePhillips** [MindscapeHQ/raygun4node#45]
To handle sending errors to raygun before an application crashes I suggest adding a sendSync method to the raygun client. This will allow the code to be wrapped in a domain, send the error to raygun and exit preventing any additional code to be run. For example, an async loop where an error you want to prevent any further execution.

```
async.each(images, function(image, next) {
  optimiseImage(image, function (err) {
    if (err) {
      raygunClient.sendSync(err);
      process.exit(1);
    }

    next();
  }
}, callback);
```

The code above will cause the error to be sent and prevent all other async optimiseImage calls to be blocked. https://github.com/ForbesLindesay/sync-request could be used to create this function.

Let me know your thoughts.

**Comment by fundead** [comment]
Firstly apologies for the delay in response to this ticket. As Node's model is heavily asynchronous we're not 100% for adding a blocking API send call, this would impact the rest of the application to a reasonable degree based on the Raygun API's current timing metric. While we aim to keep this low (currently ~80ms) this could degrade client services in the event of a catastrophic failure. Also adding Send APIs tend to encourage their usage and due to the callback nature of Node where they need to be set up correctly, if the async API isn't consumed correctly on the initial setup experience, this might lead others to implement the sync API just to get it working, where it's left there. This would mean a large perf hit due to the single-threaded nature of Node.

We'll keep an eye on this issue, if others still have this requirement and would like it please open another ticket and we'll revisit it.
