### ISSUE TITLE
expressHandler does not catch error

### ISSUE THREAD

**Issue by tobiasrichter** [MindscapeHQ/raygun4node#62]
Hi,

i tried to catch errors by `expressHandler`. But it did not work in any case.

This is my implementation.
```
app.use(function(err, req, res, next) {
   res.status(err.status || 500);
   
   var query = req.url.split('/');
   if(query[1] && query[1] == 'api')
	/* error page for api */
	res.json({
	    "status": 401,
	    "message": err.message
	});
   else
	res.render('error', {
	     message: err.message,
            error: {}
	});
});

var port = process.env.PORT || config.get('port');
var server, type;
if(process.env.NODE_ENV == 'production') {
	server = http.createServer(app);
	type = 'http';
}
else {
	server = https.createServer(credentials,app);
	type = 'https';
}

var io = socketIo(server, {transports: ['polling'], 'polling duration': 10});

app.use(raygunClient.expressHandler);

server.listen(port);

log.info('***** exp listening on port: ' + port +' type: '+type);

module.exports = app;
```

**Comment by miquelbeltran** [comment]
I think that the issue on your code example is that the `expressHandler` is added after your custom error handler, and because this one doesn't call to `next(err)`, the Raygun middleware doesn't get called.

As Express documentation says:

> The order of middleware loading is important: middleware functions that are loaded first are also executed first.

This issue should be fixed by moving the line `app.use(raygunClient.expressHandler);` to the top.
