### ISSUE TITLE
Can't pass user to error.

### ISSUE THREAD

**Issue by AMoreaux** [MindscapeHQ/raygun4node#94]
Hi,

I would like to set a user in every event when there are send. I build my reporter function like that:

```js
const raygunClient = new raygun.Client().init({
  apiKey: process.env.ERROR_REPORTER_KEY!,
  filters: ['password'],
  useHumanStringForObject: false,
});
raygunClient.user = function (req) {
  console.log('>>>>>>>>>>>');
  const request = (req as unknown) as IRequest;
  if (request.auth?.credentials?.currentUser) {
    return {
      identifier: request.auth.credentials.currentUser.id,
      email: request.auth.credentials.currentUser.email,
      username: request.auth.credentials.currentUser.username,
    };
  }
  return {};
};
```

When I execute `raygunClient.send(error)` the `raygunClient.user` is never executed. What am I doing wrong?

**Comment by Widdershin** [comment]
Thanks for the issue, I’ll be looking into this early next week.

**Comment by AMoreaux** [comment]
Hi, @Widdershin any news 🙂

**Comment by Widdershin** [comment]
@AMoreaux sorry about the delay in responding, was overloaded last week.

The `user` function is only executed when a request is passed as the fourth argument to `raygunClient.send`.

This happens automatically with errors captured by the express middleware, but for errors that are reported directly by user code, the request object should be passed to `raygunClient.send`.

For example:

```
const express = require('express');
const raygun = require('raygun');

const raygunClient = new raygun.Client().init({
  apiKey: process.env.RAYGUN_API_KEY,
});

const app = express();

app.get('/', (req, res) => {
  const error = new Error('test');
  const customData = {};

  raygunClient.send(error, customData, () => {}, req);

  res.send('done');
});

app.listen(3030, 'localhost', () => console.log('listening on 3030'));
```

I'll add a note to the README about this behaviour since it's not necessarily clear.

**Comment by AMoreaux** [comment]
Ok, I see. Thank you 👍
